# Generated by Django 5.1.3 on 2024-11-28 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_org_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='company',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveField(
            model_name='user',
            name='org',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
