# Generated by Django 5.1.3 on 2024-11-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_role_teamprofile_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LD', 'Leader'), ('MB', 'Member')], default='MB', max_length=3),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamProfile',
        ),
    ]
