# Generated by Django 5.1.3 on 2024-11-28 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_team_user_alter_teammember_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='deg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.designation'),
        ),
    ]
